### ISSUE TITLE
为什么不能下载database.db

### ISSUE THREAD

**Issue by googleman2016** [hjlarry/fastapi-vue-cms#2]

**Comment by googleman2016** [comment]
谢谢分享这个框架，学习了。当我想下载这个数据库并进一步深入学习时，系统提示没有下载权限？！记得以前下载类似文件是没有问题的，何况我已经登录了。

**Comment by hjlarry** [comment]
系统提示？ github提示？  那个文件应该就是一个sqlite数据库文件吧，有没有都无所谓的
